CREATE TABLE IF NOT EXISTS SLEEP (
DATEYMD integer PRIMARY KEY DEFAULT 0,
ENDTIME float,
STARTTIME float,
TIMEZONE varchar);
CREATE TABLE IF NOT EXISTS SLEEPSTAGE (
DATEYMD integer,
ENDTIME float,
STARTTIME float,
STAGE integer,
UNIQUE(ENDTIME,STARTTIME));
CREATE TABLE IF NOT EXISTS SLEEPPROPERTY (
DATEYMD integer UNIQUE DEFAULT 0,
AMOUNTOFSLEEP integer,
SLEEPVSAWAKE integer,
SLEEPLATENCY integer,
GOTUP integer,
WAKINGEVENTS integer,
SNORING integer,
TOTAL integer,
BPM integer,
BREATHSPM integer);