CREATE TABLE IF NOT EXISTS SLEEP (
DATEYMD integer PRIMARY KEY DEFAULT 0,
ENDTIME float DEFAULT 0,
STARTTIME float DEFAULT 0,
TOBEDTIME float DEFAULT 0,
FALLASLEEPTIME float DEFAULT 0,
TIMEZONE varchar DEFAULT '');
CREATE TABLE IF NOT EXISTS SLEEPSTAGE (
DATEYMD integer DEFAULT 0,
ENDTIME float DEFAULT 0,
STARTTIME float DEFAULT 0,
STAGE integer DEFAULT 0,
DEEPVALUE integer DEFAULT 0,
UNIQUE(ENDTIME,STARTTIME));
CREATE TABLE IF NOT EXISTS SLEEPPROPERTY (
DATEYMD integer UNIQUE DEFAULT 0,
AMOUNTOFSLEEP integer DEFAULT 0,
SLEEPVSAWAKE integer DEFAULT 0,
SLEEPLATENCY integer DEFAULT 0,
GOTUP integer DEFAULT 0,
WAKINGEVENTS integer DEFAULT 0,
SNORING integer DEFAULT 0,
TOTAL integer DEFAULT 0,
TOTALSLEEPTIME float DEFAULT 0,
BPM integer DEFAULT 0,
BREATHSPM integer DEFAULT 0);